~r/var/tmp/.homebrew:~h/.brew
~p/etc/zshrc:~h/.zshrc
~p/etc/vim:~h/.vim
~p/etc/vimrc:~h/.vimrc
~p/etc/gitconfig:~h/.gitconfig
~p/Library/Linked/Programs:~h/Programs
~p/Library/Linked/VSCode:~h/.vscode
~p/Library/JRE:~a/FjordLauncher/java
~p/opt/macvim/MacVim.app:~h/Applications/MacVim.app
~p/Library/NPM:~h/.npm
~p/Library/Linked/pipx:~h/.local/pipx
