~r/var/tmp/.homebrew:~h/.brew
~p/etc/zshrc:~h/.zshrc
~p/etc/vim:~h/.vim
~p/etc/vimrc:~h/.vimrc
~p/etc/gitconfig:~h/.gitconfig
~p/Library/Linked/Programs:~h/Programs
~p/Library/NPM:~h/.npm
~p/Library/Linked/pipx:~h/.local/pipx
~p/etc/nushell:~a/nushell
~p/Library/Cargo:~h/.cargo
~p/etc/xdg:~h/.config
~p/local/share:~h/.local/share
~p/var/lib:~h/.local/state
~h/Library/Caches:~h/.cache
~p/local/bin:~h/.local/bin
~p/Library/Linked/Programs/nixos/modules/home/desktop/apps/programs/support/nu/autoload:~p/etc/xdg/nushell/autoload
~p/local:~h/Library/Python/3.14
